version: "3.3"

services:
    # image project
    php:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            laravel-9:
                ipv4_address: 172.16.132.13
        ports:
            - "${PORT_RANGE}:${PORT_RANGE}"

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            laravel-9:
                ipv4_address: 172.16.132.12
    # db mysql
    mysql:
        image: mariadb:10.3
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "${DB_PORT_EXT}:${DB_PORT}"
        networks:
            laravel-9:
                ipv4_address: 172.16.132.11
   # redis
    redis:
        image: redis:latest
        restart: unless-stopped
        networks:
            laravel-9:
                ipv4_address: 172.16.132.10
networks:
    laravel-9:
        ipam:
            driver: default
            config:
                - subnet: 172.16.132.0/24
